apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: bin-it-right-api
    newName: bin-it-right-api
    newTag: latest
patchesStrategicMerge:
  - service-kind.yaml