apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: bin-it-right-api
    newName: europe-west10-docker.pkg.dev/bin-it-right-482413/bin-it-right/bin-it-right-api
    newTag: latest
patches:
  - path: service-gke.yaml